Repository leoviana00/GitContributionOpenSource, pull requests merged in 2024-09, with the labels that each got.

#29 feat: teste 10 pr validation
  .github/workflows/main.yml
  TESTING_PR.md
Labels: automerge

#30 feat: teste pr 10
  .github/workflows/main.yml
  TESTING_PR.md
Labels: automerge

#31 feat: ajuste action steps
  .github/workflows/main.yml
Labels: automerge

#32 feat(validation): validacao pr 12
  TESTING_PR.md
Labels: automerge

#33 doc: teste pr 13
  TESTING_PR.md
Labels: automerge

#34 feat: ajuste do step de validacao de pr
  .github/pr-title-checker-config.json
  .github/workflows/main.yml
Labels: automerge

#37 feature: Testing 16
  .github/pr-title-checker-config.json
  TESTING_PR.md
Labels: titulo está fora do padrão

#39 docs(v2): teste validate pr 20
  TESTING_PR.md
Labels: automerge

#40 feat(v09): format json title checker
  .github/pr-title-checker-config.json
Labels: titulo está fora do padrão

#41 feat(test): Testing 21 PR
  .github/pr-title-checker-config.json
  TESTING_PR.md
Labels: titulo está fora do padrão

#42 feat(validation): Testing PR 22
  .github/pr-title-checker-config.json
  TESTING_PR.md
Labels: titulo está fora do padrão

#43 feat(pr): validação de titulo e automerge PR 23
  .github/pr-title-checker-config.json
  TESTING_PR.md
Labels: titulo está fora do padrão

#44 feat(pr): Testing PR 25
  .github/pr-title-checker-config.json
  TESTING_PR.md
Labels: titulo está fora do padrão

#45 feat(pr): Testing PR 26
  TESTING_PR.md
Labels: automerge

#46 feat(teste): PR 28 Validacao
  TESTING_PR.md
Labels: automerge

#47 feat: passando um titulo fora do padrao
  TESTING_PR.md
Labels: automerge

#49 fix(validate): fora padrao
  TESTING_PR.md
Labels: automerge

#50 fix: Adicionando novos prefixos ao arquivo de configuracao title chec…
  .github/pr-title-checker-config.json
Labels: automerge

#51 docs(contributors): Update Readme
  README.md
Labels: automerge

#54 docs(pr): Update Template PR
  .github/pull_request_template.md
  CONTRIBUTING.md
  contribution_project.md
Labels: automerge

#55 feat(pr): teste pr
  .github/pull_request_template.md
  contribution_project.md
Labels: automerge

#56 docs(contruibuicao): Update Guia do contribuidor
  CONTRIBUTING.md
Labels: automerge

#57 docs(readme): update readme
  README.md
Labels: automerge

#58 docs(fix): correcao do link de contribuicao
  README.md
Labels: automerge

#59 fix(moura): ajuste de texto teste
  contribution_project.md
Labels: automerge

#60 fix(moura): correcao da exibicao dos contribuidores
  README.md
Labels: automerge

#61 docs(license): add license file
  LICENSE
Labels: automerge

#64 feat(template): ajuste templates issue
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: automerge

#65 feat(teste): contrib 1
  contribution_project.md
Labels: automerge

#66 feat(contrib): contribution1
  contribution_project.md
Labels: automerge

#67 docs(contrib): contrib 2
  contribution_project.md
Labels: automerge

#68 feat(contrib): contrib 2
  contribution_project.md
Labels: automerge

#69 feat(contrib): contribuicao3
  contribution_project.md
Labels: automerge

#71 docs(contribution): Atualizacao do guia do contribuidor
  CONTRIBUTING.md
  README.md
Labels: automerge

#72 docs(readme): Update roadmap readme
  README.md
Labels: automerge

#73 feat(actions): add validacao de arquivos modificados
  .github/workflows/main.yml
Labels: automerge

#81 docs(contrib): contribution 1
  contribution_project.md
Labels: automerge

#84 docs(contrib): contrib 1
  contribution_project.md
Labels: automerge

#86 docs(contrib): Validation action
  contribution_project.md
Labels: automerge

#90 feat(contribution): Contribution 1
  contribution_project.md
Labels: automerge

#92 docs(readme): Update readme
  README.md
Labels: file not allowed

#93 feat(contrib): contribution 2
  contribution_project.md
Labels: automerge

#94 docs(security): add securitymd
  SECURITY.md
Labels: file not allowed

#95 docs(readme): update readme
  README.md
Labels: file not allowed

#97 docs(securit): add files security
  .github/config.yml
  CONTRIBUTING.md
  SECURITY.md
Labels: file not allowed

#98 feat(issues): Ajuste templates issues
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
Labels: file not allowed

#100 docs(configs): ajustando configs issues templates
  .github/ISSUE_TEMPLATE/config.yml
Labels: file not allowed

#101 docs(config): add config para redirecinar ao forum
  .github/ISSUE_TEMPLATE/config.yml
Labels: file not allowed

#102 docs(readme): update readme
  CONTRIBUTING.md
  README.md
Labels: file not allowed

#103 docs(readme): correcao readme
  README.md
Labels: file not allowed

#104 feat(contributionnn): Adicionando contribuicao 3
  contribution_project.md
Labels: automerge

#105 docs: new contribution
  contribution_project.md
Labels: automerge

#106 feat: new contrib
  contribution_project.md
Labels: automerge
